export const DESIGN_SYSTEM_NAV = [
  {
    label: "Foundations",
    items: [
      { href: "/design-system/foundations/typography", label: "Typography" },
      { href: "/design-system/foundations/color", label: "Color" },
      { href: "/design-system/foundations/borders", label: "Borders" },
    ],
  },
  {
    label: "Components",
    items: [
      { href: "/design-system/components/badges", label: "Tags" },
      { href: "/design-system/components/loading", label: "Loading Indicator" },
      { href: "/design-system/components/buttons", label: "Buttons" },
      { href: "/design-system/components/fields", label: "Fields" },
      { href: "/design-system/components/empty-state", label: "Empty state" },
      { href: "/design-system/components/checkbox", label: "Checkbox" },
      { href: "/design-system/components/radio-buttons", label: "Radio buttons" },
      { href: "/design-system/components/dropdown", label: "Menu" },
      { href: "/design-system/components/modal", label: "Modal" },
      { href: "/design-system/components/tooltip", label: "Tooltip" },
      { href: "/design-system/components/accordions", label: "Accordions" },
      { href: "/design-system/components/tabs", label: "Tab Group" },
      { href: "/design-system/components/selectable-cards", label: "Selectable cards" },
      { href: "/design-system/components/table", label: "Table" },
      { href: "/design-system/components/pagination", label: "Pagination" },
      { href: "/design-system/components/toggles", label: "Toggles" },
      { href: "/design-system/components/pills", label: "Selection Chips" },
      { href: "/design-system/components/progress-bar", label: "Progress bar" },
      { href: "/design-system/components/callouts", label: "Page Notifications" },
      { href: "/design-system/components/toasts", label: "Toast Notification" },
    ],
  },
] as const;
